name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-javascript:
    name: JavaScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.OWNER }}:role/github_action_role_for_publish_code_artifact
          role-session-name: samplerolesession
          aws-region: ${{ secrets.REGION }}
          
      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          domain: ${{ secrets.DOMAIN }}
          domain-owner: ${{ secrets.OWNER }}
          region: ${{ secrets.REGION }}
          repository: ${{ secrets.REPO_NAME }}
          format: 'generic'
          package_name: 'github-test'
          package_version: '0.0.1'
          folder: './dist'
          